@startuml class

class NguoiDung {
    - id: int
    - taiKhoan: string
    - matKhau: string
    - email: string
    - soDt: string
    - maNhom: string
    - maLoaiNguoiDung: string
    - hoTen: string
    - otp: string
    - daXacThuc: bool
    - otpCreatedAt: datetime
    + dangNhap(): bool
    + dangXuat(): void
    + doiMatKhau(): bool
    + xacThucEmail(): bool
    + getthongTin()
    + isDaXacThuc(): bool
}
class Banner {
    - id: int 
    - hinhAnh : string 
    - maPhim : string 
    + themBanner (id,hinhAnh,maPhim):bool
    + xoaBanner(id):bool
}
class TinTuc {
    - id: int
    - tieude: string
    - noidung: text
    - hinhAnh: string
    - ngayDang: timestamp
    + getDanhSachTinTuc(): List<TinTuc>
    + themTinTuc(tieude, noidung, hinhAnh): bool
    + suaTinTuc(tintucId, tieude, noidung, hinhAnh): bool
    + xoaTinTuc(tintucId): bool
}

class CumRap {
    - cid: int
    - maCumRap: string
    - tenCumRap: string
    - diaChi: string
    + themCumRap(...): bool
    + suaCumRap(cid, ...): bool
    + xoaCumRap(cid): bool
}

class DanhSachRap {
    - did: int
    - maRap: string
    - tenRap: string
    - maCumRap: int
    + themRap(...): bool
    + suaRap(did, ...): bool
    + xoaRap(did): bool
}

class HeThongRap {
    - hid: int
    - maHeThongRap: string
    - tenHeThongRap: string
    - biDanh: string
    - logo: string
    + themHeThongRap(...): bool
    + suaHeThongRap(hid, ...): bool
    + xoaHeThongRap(hid): bool
}

class LichChieuInsert {
    - maLichChieu: int
    - ngayChieuGioChieu: string
    - maRap: int
    - tenRap: string
    - giaVe: double
    - thoiLuong: int
    + themLichChieu(...): bool
    + suaLichChieu(maLichChieu, ...): bool
    + xoaLichChieu(maLichChieu): bool
}

class DatVe {
    - maGhe: int
    - tenGhe: string
    - loaiGhe: string
    - giaVe: double
    - taiKhoanNguoiDat: string
    - maLichChieu: int
    + datVe(maLichChieu, dsGhe): bool
    + huyVe(maGhe): bool
    + timVeTrong(maLichChieu): List<int>
}

class LichChieu {
    - plid: int
    - chi_tiet_phim: ChiTietPhim
    - lichchieuinsert: LichChieuInsert
    + layLichChieuPhim(maPhim): List<LichChieu>
}

class CumRapVaLichChieu {
    - clid: int
    - cumrap: CumRap
    - lichchieuinsert: LichChieuInsert
    + layLichChieuCumRap(maCumRap): List<LichChieu>
}

class HeThongRapVaCumRap {
    - hcid: int
    - hethongrap: HeThongRap
    - cumrap: CumRap
    + layCumRapTheoHeThongRap(maHeThongRap): List<CumRap>
}

class HeThongRapVaPhim {
    - hpid: int
    - maHeThongRap: HeThongRap
    - maPhim: ChiTietPhim
    + layPhimTheoHeThongRap(maHeThongRap): List<ChiTietPhim>
}
class danhGia {
    -id : int
    -hoTen: string
    -email:string
    -noiDung:string
    -maPhim: maPhim
    -thoiGian: int
    + themDanhGia() :bool
}
class ChiTietPhim {
- maPhim: int
- tenPhim: string
- biDanh: string
- trailer: string
- hinhAnh: string
- moTa: string
- daoDien: string
- dienVien: string
- quocGia: string
- theLoai: string
- dinhDang: string
- maNhom: string
- ngayKhoiChieu: string
- danhGia: int
+ themPhim(...): bool
+ suaPhim(maPhim, ...): bool
+ xoaPhim(maPhim): bool
}

class NhanVien {
- id: int
- hoTen: string
- ngaySinh: date
- email: string
- soDT: string
- diaChi: string
- ngayVaoLam: date
- loaiNhanVien: string
- noiLamViec: int
- luong: double
- trangThai: boolean
+ themNhanVien(...): bool
+ suaNhanVien(id, ...): bool
+ xoaNhanVien(id): bool
+ getDanhSachNhanVien(): List<NhanVien>
}
NguoiDung "1" *-- "0..n" DatVe
ChiTietPhim "1" *-- "0..n" LichChieu
CumRap "1" *-- "1..n" DanhSachRap
DanhSachRap "1" *-- "1..n" LichChieuInsert
LichChieuInsert "1" *-- "1..n" DatVe
HeThongRap "1" *-- "1..n" CumRap
HeThongRap "1" *-- "1..n" ChiTietPhim
Banner "1"*--"1" ChiTietPhim
danhGia "1"*--"1" ChiTietPhim
NhanVien "1" *-- "1" CumRap
@enduml
